Book
Paradoxallist/bookshop pull request #2
Opened 2024-03-19 17:42 UTC by Paradoxallist

implement entity book

2024-03-19 17:48 UTC, Vladyslav-Kuksiuk commented on pom.xml
> +		<java.version>17</java.version>
123

2024-03-20 09:13 UTC, Rommelua requested changes

2024-03-20 09:13 UTC, Rommelua commented on src/main/java/store/bookshop/model/Book.java
> +@Data
Do not use Data with entity class.
Add Getter, Setter, etc.

2024-03-20 09:13 UTC, Rommelua commented on src/main/java/store/bookshop/model/Book.java
> +    }
use lombok for constructors

2024-03-20 09:13 UTC, Rommelua commented on src/main/java/store/bookshop/model/Book.java
> +    private String isbn;
```suggestion
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "author", nullable = false)
    private String author;
    @Column(name = "isbn", nullable = false, unique = true)
    private String isbn;
```

2024-03-20 18:46 UTC, kerrrusha approved these changes

2024-03-21 00:28 UTC, merged